#!/usr/bin/env python

import sys, subprocess

# Decleration host
hosts = {
    'action  ': '134.212.28.32',
    'ressac1 ': '134.212.244.176',
    'ressac2 ': '134.212.244.178',
    'station1': '134.212.244.34',
    'station2': '134.212.244.35',
    'minode  ': '134.212.244.36',
    'mana    ': '127.0.0.1',
    'minnie  ': '127.0.0.1',
    'ap-wifi1': '134.212.244.109',
    'ap-wifi2': '134.212.244.110'
}

# xterm color
class TColor:
    red = '\033[31m'
    green = '\033[32m'
    blue = '\033[33m'
    endc = '\033[0m'
    
def ping(ip):
    ret = subprocess.call("ping -c 1 -w 1 %s" % ip,
            shell=True,
            stdout=open('/dev/null', 'w'),
            stderr=subprocess.STDOUT)
    if ret == 0:
        return True
    else:
        return False


def main():
    for host, ip in hosts.iteritems():
        if not ping(ip):
            print(TColor.red
                  +"{0:10} {1:16} Dead !!!".format(host, ip)
                  +TColor.endc)
            #sys.exit(1)
        else:
            print(TColor.green
                  +"{0:10} {1:16} Alive".format(host, ip)
                  +TColor.endc)

if __name__ == '__main__':
    main()
