# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Thu Sep 17 14:25:49 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(992, 885)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mapViewer = MapViewer(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapViewer.sizePolicy().hasHeightForWidth())
        self.mapViewer.setSizePolicy(sizePolicy)
        self.mapViewer.setObjectName("mapViewer")
        self.horizontalLayout.addWidget(self.mapViewer)
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(300, 650))
        self.frame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.comCheckBox = QtGui.QCheckBox(self.groupBox)
        self.comCheckBox.setEnabled(True)
        self.comCheckBox.setChecked(True)
        self.comCheckBox.setTristate(False)
        self.comCheckBox.setObjectName("comCheckBox")
        self.horizontalLayout_11.addWidget(self.comCheckBox)
        self.trailCheckBox = QtGui.QCheckBox(self.groupBox)
        self.trailCheckBox.setChecked(True)
        self.trailCheckBox.setObjectName("trailCheckBox")
        self.horizontalLayout_11.addWidget(self.trailCheckBox)
        self.trajCheckBox = QtGui.QCheckBox(self.groupBox)
        self.trajCheckBox.setObjectName("trajCheckBox")
        self.horizontalLayout_11.addWidget(self.trajCheckBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setEnabled(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.transparencySlider = QtGui.QSlider(self.groupBox)
        self.transparencySlider.setEnabled(True)
        self.transparencySlider.setMaximum(100)
        self.transparencySlider.setProperty("value", 70)
        self.transparencySlider.setOrientation(QtCore.Qt.Horizontal)
        self.transparencySlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.transparencySlider.setObjectName("transparencySlider")
        self.verticalLayout_4.addWidget(self.transparencySlider)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vnetReloadButton = QtGui.QPushButton(self.groupBox_2)
        self.vnetReloadButton.setObjectName("vnetReloadButton")
        self.verticalLayout_2.addWidget(self.vnetReloadButton)
        self.startButton = QtGui.QPushButton(self.groupBox_2)
        self.startButton.setEnabled(False)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_2.addWidget(self.startButton)
        self.stopButton = QtGui.QPushButton(self.groupBox_2)
        self.stopButton.setEnabled(True)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout_2.addWidget(self.stopButton)
        self.line = QtGui.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ubComField = QtGui.QLineEdit(self.groupBox_2)
        self.ubComField.setMaximumSize(QtCore.QSize(40, 16777215))
        self.ubComField.setObjectName("ubComField")
        self.horizontalLayout_8.addWidget(self.ubComField)
        self.ubComButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ubComButton.sizePolicy().hasHeightForWidth())
        self.ubComButton.setSizePolicy(sizePolicy)
        self.ubComButton.setObjectName("ubComButton")
        self.horizontalLayout_8.addWidget(self.ubComButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ubTargetField = QtGui.QLineEdit(self.groupBox_2)
        self.ubTargetField.setMaximumSize(QtCore.QSize(40, 16777215))
        self.ubTargetField.setObjectName("ubTargetField")
        self.horizontalLayout_9.addWidget(self.ubTargetField)
        self.ubTargetButton = QtGui.QPushButton(self.groupBox_2)
        self.ubTargetButton.setObjectName("ubTargetButton")
        self.horizontalLayout_9.addWidget(self.ubTargetButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.paramLoadButton = QtGui.QPushButton(self.groupBox_2)
        self.paramLoadButton.setObjectName("paramLoadButton")
        self.verticalLayout_2.addWidget(self.paramLoadButton)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.frame)
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtGui.QToolBox(self.groupBox_3)
        self.toolBox.setObjectName("toolBox")
        self.page = QtGui.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 254, 269))
        self.page.setObjectName("page")
        self.gridLayout = QtGui.QGridLayout(self.page)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.killedRobotBox = QtGui.QComboBox(self.page)
        self.killedRobotBox.setObjectName("killedRobotBox")
        self.gridLayout.addWidget(self.killedRobotBox, 0, 1, 1, 1)
        self.warnedKilledRobotBox = QtGui.QComboBox(self.page)
        self.warnedKilledRobotBox.setObjectName("warnedKilledRobotBox")
        self.gridLayout.addWidget(self.warnedKilledRobotBox, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.page)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.killButton = QtGui.QPushButton(self.page)
        self.killButton.setObjectName("killButton")
        self.gridLayout.addWidget(self.killButton, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtGui.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 254, 269))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vnetRobotBox = QtGui.QComboBox(self.page_2)
        self.vnetRobotBox.setObjectName("vnetRobotBox")
        self.horizontalLayout_2.addWidget(self.vnetRobotBox)
        self.vnetIsolateButton = QtGui.QPushButton(self.page_2)
        self.vnetIsolateButton.setObjectName("vnetIsolateButton")
        self.horizontalLayout_2.addWidget(self.vnetIsolateButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.vnetRangeField = QtGui.QLineEdit(self.page_2)
        self.vnetRangeField.setMaximumSize(QtCore.QSize(40, 16777215))
        self.vnetRangeField.setObjectName("vnetRangeField")
        self.horizontalLayout_12.addWidget(self.vnetRangeField)
        self.vnetRangeButton = QtGui.QPushButton(self.page_2)
        self.vnetRangeButton.setObjectName("vnetRangeButton")
        self.horizontalLayout_12.addWidget(self.vnetRangeButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.vnetBlockButton = QtGui.QPushButton(self.page_2)
        self.vnetBlockButton.setObjectName("vnetBlockButton")
        self.verticalLayout_6.addWidget(self.vnetBlockButton)
        self.vnetResetButton = QtGui.QPushButton(self.page_2)
        self.vnetResetButton.setObjectName("vnetResetButton")
        self.verticalLayout_6.addWidget(self.vnetResetButton)
        self.vnetInfoLabel = QtGui.QLabel(self.page_2)
        self.vnetInfoLabel.setText("")
        self.vnetInfoLabel.setObjectName("vnetInfoLabel")
        self.verticalLayout_6.addWidget(self.vnetInfoLabel)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtGui.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 254, 269))
        self.page_3.setObjectName("page_3")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtGui.QLabel(self.page_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.targetRobotBox = QtGui.QComboBox(self.page_3)
        self.targetRobotBox.setObjectName("targetRobotBox")
        self.horizontalLayout_5.addWidget(self.targetRobotBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtGui.QLabel(self.page_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.targetXField = QtGui.QLineEdit(self.page_3)
        self.targetXField.setMaximumSize(QtCore.QSize(40, 16777215))
        self.targetXField.setObjectName("targetXField")
        self.horizontalLayout_6.addWidget(self.targetXField)
        self.targetYField = QtGui.QLineEdit(self.page_3)
        self.targetYField.setMaximumSize(QtCore.QSize(40, 16777215))
        self.targetYField.setObjectName("targetYField")
        self.horizontalLayout_6.addWidget(self.targetYField)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.targetSendButton = QtGui.QPushButton(self.page_3)
        self.targetSendButton.setObjectName("targetSendButton")
        self.verticalLayout_7.addWidget(self.targetSendButton)
        self.line_2 = QtGui.QFrame(self.page_3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_7.addWidget(self.line_2)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.targetEndBox = QtGui.QComboBox(self.page_3)
        self.targetEndBox.setObjectName("targetEndBox")
        self.horizontalLayout_15.addWidget(self.targetEndBox)
        self.targetEndButton = QtGui.QPushButton(self.page_3)
        self.targetEndButton.setObjectName("targetEndButton")
        self.horizontalLayout_15.addWidget(self.targetEndButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.targetTrackBox = QtGui.QComboBox(self.page_3)
        self.targetTrackBox.setObjectName("targetTrackBox")
        self.horizontalLayout_13.addWidget(self.targetTrackBox)
        self.targetTrackButton = QtGui.QPushButton(self.page_3)
        self.targetTrackButton.setObjectName("targetTrackButton")
        self.horizontalLayout_13.addWidget(self.targetTrackButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.targetRepairBox = QtGui.QComboBox(self.page_3)
        self.targetRepairBox.setObjectName("targetRepairBox")
        self.horizontalLayout_14.addWidget(self.targetRepairBox)
        self.targetRepairButton = QtGui.QPushButton(self.page_3)
        self.targetRepairButton.setObjectName("targetRepairButton")
        self.horizontalLayout_14.addWidget(self.targetRepairButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtGui.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 254, 269))
        self.page_4.setObjectName("page_4")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtGui.QLabel(self.page_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.debugRobotBox = QtGui.QComboBox(self.page_4)
        self.debugRobotBox.setObjectName("debugRobotBox")
        self.horizontalLayout_3.addWidget(self.debugRobotBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.debugStateBox = QtGui.QComboBox(self.page_4)
        self.debugStateBox.setObjectName("debugStateBox")
        self.horizontalLayout_7.addWidget(self.debugStateBox)
        self.debugStateSend = QtGui.QPushButton(self.page_4)
        self.debugStateSend.setObjectName("debugStateSend")
        self.horizontalLayout_7.addWidget(self.debugStateSend)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.debugSendUpdateButton = QtGui.QPushButton(self.page_4)
        self.debugSendUpdateButton.setObjectName("debugSendUpdateButton")
        self.horizontalLayout_4.addWidget(self.debugSendUpdateButton)
        self.debugRepairButton = QtGui.QPushButton(self.page_4)
        self.debugRepairButton.setObjectName("debugRepairButton")
        self.horizontalLayout_4.addWidget(self.debugRepairButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.debugSendGeneralUpdateButton = QtGui.QPushButton(self.page_4)
        self.debugSendGeneralUpdateButton.setObjectName("debugSendGeneralUpdateButton")
        self.horizontalLayout_10.addWidget(self.debugSendGeneralUpdateButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.toolBox.addItem(self.page_4, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 992, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ISMAC", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Affichage", None, QtGui.QApplication.UnicodeUTF8))
        self.comCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Com.", None, QtGui.QApplication.UnicodeUTF8))
        self.trailCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Traces", None, QtGui.QApplication.UnicodeUTF8))
        self.trajCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Traj.", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Transparence", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Opérateur Mission", None, QtGui.QApplication.UnicodeUTF8))
        self.vnetReloadButton.setText(QtGui.QApplication.translate("MainWindow", "MàJ vNet", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("MainWindow", "Début mission", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Fin mission", None, QtGui.QApplication.UnicodeUTF8))
        self.ubComButton.setText(QtGui.QApplication.translate("MainWindow", "Attente max. com (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.ubTargetButton.setText(QtGui.QApplication.translate("MainWindow", "Durée max. suivi cible (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.paramLoadButton.setText(QtGui.QApplication.translate("MainWindow", "Recharger paramètres", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Opérateur simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Robot tué", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Robot informé", None, QtGui.QApplication.UnicodeUTF8))
        self.killButton.setText(QtGui.QApplication.translate("MainWindow", "Tuer", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), QtGui.QApplication.translate("MainWindow", "Robot Mort", None, QtGui.QApplication.UnicodeUTF8))
        self.vnetIsolateButton.setText(QtGui.QApplication.translate("MainWindow", "Isoler", None, QtGui.QApplication.UnicodeUTF8))
        self.vnetRangeField.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.vnetRangeButton.setText(QtGui.QApplication.translate("MainWindow", "Limiter portée com.", None, QtGui.QApplication.UnicodeUTF8))
        self.vnetBlockButton.setText(QtGui.QApplication.translate("MainWindow", "Tout bloquer", None, QtGui.QApplication.UnicodeUTF8))
        self.vnetResetButton.setText(QtGui.QApplication.translate("MainWindow", "Tout autoriser", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), QtGui.QApplication.translate("MainWindow", "Communications (vNet)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Robot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Position (x,y)", None, QtGui.QApplication.UnicodeUTF8))
        self.targetXField.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "236", None, QtGui.QApplication.UnicodeUTF8))
        self.targetYField.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "-9", None, QtGui.QApplication.UnicodeUTF8))
        self.targetSendButton.setText(QtGui.QApplication.translate("MainWindow", "Emuler une détection", None, QtGui.QApplication.UnicodeUTF8))
        self.targetEndButton.setText(QtGui.QApplication.translate("MainWindow", "Fin du suivi", None, QtGui.QApplication.UnicodeUTF8))
        self.targetTrackButton.setText(QtGui.QApplication.translate("MainWindow", "Suivre cible", None, QtGui.QApplication.UnicodeUTF8))
        self.targetRepairButton.setText(QtGui.QApplication.translate("MainWindow", "Reprendre mission", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), QtGui.QApplication.translate("MainWindow", "Détection de cible", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Robot", None, QtGui.QApplication.UnicodeUTF8))
        self.debugStateSend.setText(QtGui.QApplication.translate("MainWindow", "Envoyer", None, QtGui.QApplication.UnicodeUTF8))
        self.debugSendUpdateButton.setText(QtGui.QApplication.translate("MainWindow", "Envoyer \n"
"MàJ STN", None, QtGui.QApplication.UnicodeUTF8))
        self.debugRepairButton.setText(QtGui.QApplication.translate("MainWindow", "Réparation", None, QtGui.QApplication.UnicodeUTF8))
        self.debugSendGeneralUpdateButton.setText(QtGui.QApplication.translate("MainWindow", "Envoyer MàJ STN générale", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), QtGui.QApplication.translate("MainWindow", "Debug", None, QtGui.QApplication.UnicodeUTF8))

from map_viewer import MapViewer
